- id: custom-secret-regex
  name: Custom Secret Regex
  entry: secret-scan
  language: python
  pass_filenames: false
  description: Scan staged files for secrets (passwords, tokens, UUIDs, etc.)
  files: '\.(py|java|js|ts|json|ya?ml|env|properties|sh)$'
