repos:
  - repo: local
    hooks:
      - id: detect-secrets-local
        name: Detect Secrets (Local)
        entry: bash -c "git diff --cached --name-only | xargs detect-secrets scan"
        language: system
        pass_filenames: false
      - id: custom-secret-regex
        name: Custom Secret Regex
        entry: python .githooks/secret_scan.py
        language: system
        files: '\.(py|java|js|ts|json|yaml|yml|env|properties|sh)$'
